apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_LABEL}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: ${APP_LABEL}
  template:
    metadata:
      labels:
        app: ${APP_LABEL}
    spec:
      nodeSelector:
        kubernetes.io/hostname: "${NODE_HOSTNAME}"
      containers:
      - name: busybox
        image: ${IMAGE}
        command: ["/bin/sh", "-c", "sleep infinity"]
        volumeMounts:
        - name: cache-volume
          mountPath: "${MOUNT_PATH}"
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: ${PVC_NAME}
      # imagePullSecrets:
      #   - name: your-registry-secret
